### ISSUE TITLE
Missing docker-compose docker images

### ISSUE THREAD

**Issue by baptabl** [osm-without-borders/cosmogony_explorer#23]
Hi,

Docker images for `osmwithoutborders/cosmogony-tiles` and `osmwithoutborders/cosmogony-api` used in the docker-compose.yml seem to be missing on docker hub. Are they elsewhere? Are they private? Am I missing something?

Thanks,
Baptiste

**Comment by antoine-de** [comment]
Salut Baptiste,

The docker images are now currently automatically pushed to dockerhub, you need to build them locally the first time.

To do this, you need to do:

```bash
PATH_TO_COSMOGONY_DIR=./<directory with the data> pipenv run inv -e run-local --cosmogony-file-name=<name of the cosmogony file> --build-dockers
```

Sorry the readme is not straightforward enough on this :disappointed: 


By curiosity what do you want to do with cosmogony?
